name: Release
on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            git \
            qt6-base-dev \
            qt6-base-private-dev \
            qt6-tools-dev \
            qt6-wayland \
            libgl1-mesa-dev \
            libx11-dev \
            libxcb1-dev \
            libxkbcommon-dev \
            libwayland-dev

    - name: Build project
      run: |
        make build

    - name: Upload x86-64 binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/pwrctl
        asset_name: pwrctl-${{ github.ref_name }}
        tag: ${{ github.ref }}
