name: Release
on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            git \
            qt6-base-dev \
            qt6-base-private-dev \
            qt6-tools-dev \
            qt6-wayland \
            libgl1-mesa-dev \
            libx11-dev \
            libxcb1-dev \
            libxkbcommon-dev \
            libwayland-dev

    - name: Build project
      run: |
        make build

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        generate_release_notes: true
        files: |
          dist/pwrctl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
